language: python
python:
   - 3.7
   - 3.8
before_install:
   - python --version
   - pip install -U pip
   - pip install -U pytest
   - pip install codecov
install:
   - pip install -r requirements.txt
   - python setup.py install
script:
   - py.test
os:
   - bionic
after_success:
   - codecov
